version: "3"
services: 
  database:
    image: postgres
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: development
      POSTGRES_USER: development
      POSTGRES_DB: development
    networks: 
      - host
    volumes:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql

networks: 
  host:
    driver: bridge
    
