version: "3"
services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: development
      POSTGRES_USER: development
      POSTGRES_DB: development
    volumes:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    mem_limit: 1024m
    cpus: 1

  frotend:
    image: node:alpine
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/node/app
    working_dir: /home/node/app
    command: yarn dev

  backend:
    image: node:alpine
    ports:
      - 3001:3001
    volumes:
      - ./backend:/home/node/app
    working_dir: /home/node/app
    command: yarn dev
