version: "3"
services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: root
    volumes:
      - ./database/backup:/var/lib/postgresql/data

  frotend:
    build: ./frontend
    ports:
      - 80:3000

  backend:
    build: ./backend
    ports:
      - 3001:3001
    restart: unless-stopped
