version: "3"
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: root
    networks:
      - app

  frotend:
    image: node:alpine
    ports:
      - 80:3000
    volumes:
      - ./frontend:/home/node/app
    working_dir: /home/node/app
    command: yarn dev
    networks:
      - app

  backend:
    image: node:alpine
    volumes:
      - ./backend:/home/node/app
    working_dir: /home/node/app
    command: yarn start:dev
    ports:
      - 3001:3001
    networks:
      - app

networks:
  app:
    driver: bridge
