version: "3"
services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: root

  frotend:
    image: node:alpine
    ports:
      - 80:3000
    volumes:
      - ./frontend:/home/node/app
    working_dir: /home/node/app
    command: yarn dev

  backend:
    image: node:alpine
    ports:
      - 3001:3001
    volumes:
      - ./backend:/home/node/app
    working_dir: /home/node/app
    command: yarn start:dev
