name: Backend Electro
on: push
jobs:
  BackendTest:
    runs-on: ubuntu-latest
    container: node:alpine
    services:
      database:
        image: postgres
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
          POSTGRES_DB: root
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run test
        run: yarn test
